package com.packetanalyzer.cli;
import com.packetanalyzer.capture.*;import com.packetanalyzer.packet.*;import com.packetanalyzer.dpi.*;import com.packetanalyzer.flow.*;import com.packetanalyzer.firewall.*;import com.packetanalyzer.stats.*;import com.packetanalyzer.web.RealtimeServer;import java.util.*;import java.util.concurrent.*;
public final class Main {
 static void usage(){System.out.println("Packet Analyzer Java 1.0\nUsage:\n  java -jar packet-analyzer.jar show input.pcap [-n N]\n  java -jar packet-analyzer.jar analyze input.pcap -o output.pcap [-r rules.conf] [-t threads]\n  java -jar packet-analyzer.jar rules rules.conf --block-ip IP --block-port PORT --block-domain DOMAIN --block-app APP\n  java -jar packet-analyzer.jar server [port]");}
 public static void main(String[]a)throws Exception{if(a.length<1){usage();return;}switch(a[0].toLowerCase()){case"show"->show(a);case"analyze"->analyze(a);case"rules"->rules(a);case"server"->RealtimeServer.main(a.length>1?new String[]{a[1]}:new String[0]);default->usage();}}
 static void show(String[]a)throws Exception{int n=10;for(int i=2;i+1<a.length;i++)if(a[i].equals("-n"))n=Integer.parseInt(a[i+1]);try(PcapReader r=new PcapReader(a[1])){for(int i=0;i<n;i++){Packet p=r.next();if(p==null)break;ParsedPacket x=PacketParser.parse(p.data);if(x==null){System.out.println(i+1+": malformed");continue;}System.out.printf("%d %s %s:%d -> %s:%d len=%d flags=%s%n",i+1,x.protocolName(),x.srcIp,x.srcPort,x.dstIp,x.dstPort,p.data.length,PacketParser.flags(x.tcpFlags));}}}
 static void analyze(String[]a)throws Exception{String in=a[1],out=null,rules=null;int threads=Math.max(1,Runtime.getRuntime().availableProcessors());for(int i=2;i<a.length;i++){switch(a[i]){case"-o"->out=a[++i];case"-r"->rules=a[++i];case"-t"->threads=Integer.parseInt(a[++i]);}}if(out==null)out="filtered.pcap";RuleManager rm=new RuleManager();if(rules!=null)rm.load(rules);Statistics st=new Statistics();ConnectionTracker tracker=new ConnectionTracker();try(PcapReader pr=new PcapReader(in);PcapWriter pw=new PcapWriter(out)){var exec=Executors.newFixedThreadPool(threads);List<Future<Decision>> fs=new ArrayList<>();Packet p;while((p=pr.next())!=null){final Packet packet=p;fs.add(exec.submit(()->process(packet,tracker,rm,st)));if(fs.size()>=threads*4){for(Future<Decision> f:fs)if(f.get().forward)pw.write(f.get().packet);fs.clear();}}for(Future<Decision>f:fs)if(f.get().forward)pw.write(f.get().packet);exec.shutdown();}System.out.println(st.report());System.out.println("Active flows: "+tracker.size());System.out.println("Output: "+out);System.out.println("Rules: "+rm.summary());}
 record Decision(Packet packet,boolean forward){} static Decision process(Packet p,ConnectionTracker t,RuleManager r,Statistics st){st.total.increment();st.bytes.add(p.data.length);ParsedPacket x=PacketParser.parse(p.data);if(x==null||!x.hasIp){st.forwarded.increment();return new Decision(p,true);}FlowKey k=new FlowKey(x.srcIp,x.dstIp,x.srcPort,x.dstPort,x.protocol);Connection c=t.get(k);c.update(p.data.length);DpiInspector.Result z=DpiInspector.inspect(x);if(!z.domain().isEmpty())c.domain=z.domain();c.app=z.app().name();boolean block=r.blocked(x.srcIp,x.dstIp,x.srcPort,x.dstPort,z.app(),z.domain());c.blocked|=block;st.app(z.app().name());if(block){st.dropped.increment();return new Decision(p,false);}st.forwarded.increment();return new Decision(p,true);}
 static void rules(String[]a)throws Exception{RuleManager rm=new RuleManager();String f=a[1];for(int i=2;i<a.length;i++){switch(a[i]){case"--block-ip"->rm.blockIp(a[++i]);case"--block-port"->rm.blockPort(Integer.parseInt(a[++i]));case"--block-domain"->rm.blockDomain(a[++i]);case"--block-app"->rm.blockApp(Application.valueOf(a[++i].toUpperCase()));}}System.out.println("Rules loaded in memory: "+rm.summary()+". Use a rules.conf file for persistence.");}}
