package com.packetanalyzer.dpi;
import com.packetanalyzer.packet.*; import java.nio.charset.*; import java.util.*; import java.util.regex.*;
public final class DpiInspector {
 public record Result(Application app,String domain){}
 private static final Map<String,Application> APPS=Map.ofEntries(Map.entry("google",Application.GOOGLE),Map.entry("youtube",Application.YOUTUBE),Map.entry("facebook",Application.FACEBOOK),Map.entry("twitter",Application.TWITTER),Map.entry("x.com",Application.TWITTER),Map.entry("instagram",Application.INSTAGRAM),Map.entry("netflix",Application.NETFLIX),Map.entry("amazon",Application.AMAZON),Map.entry("microsoft",Application.MICROSOFT),Map.entry("apple",Application.APPLE),Map.entry("whatsapp",Application.WHATSAPP),Map.entry("telegram",Application.TELEGRAM),Map.entry("tiktok",Application.TIKTOK),Map.entry("spotify",Application.SPOTIFY),Map.entry("zoom",Application.ZOOM),Map.entry("discord",Application.DISCORD),Map.entry("github",Application.GITHUB),Map.entry("cloudflare",Application.CLOUDFLARE));
 public static Result inspect(ParsedPacket p){if(p==null||p.raw==null||p.payloadLength<=0)return new Result(base(p),"");String s=new String(p.raw,p.payloadOffset,p.payloadLength,StandardCharsets.ISO_8859_1);String domain=""; if(p.hasTcp && (p.srcPort==80||p.dstPort==80)){Matcher m=Pattern.compile("(?im)^Host\\s*:\\s*([^\\r\\n:]+)").matcher(s);if(m.find())domain=m.group(1).trim();} if(p.hasUdp&&(p.srcPort==53||p.dstPort==53)){domain=dns(s.getBytes(StandardCharsets.ISO_8859_1));} if(p.hasTcp&&(p.srcPort==443||p.dstPort==443)){String sn=sni(p.raw,p.payloadOffset,p.payloadLength);if(sn!=null)domain=sn;} Application a=classify(domain); if(a==Application.UNKNOWN && p.hasTcp&&(p.srcPort==443||p.dstPort==443))a=Application.TLS; if(a==Application.UNKNOWN&&p.hasUdp&&(p.srcPort==443||p.dstPort==443))a=Application.QUIC; return new Result(a,domain);}
 static Application base(ParsedPacket p){if(p==null)return Application.UNKNOWN;if(p.hasUdp&&(p.srcPort==53||p.dstPort==53))return Application.DNS;if(p.hasTcp&&(p.srcPort==80||p.dstPort==80))return Application.HTTP;if(p.hasTcp&&(p.srcPort==443||p.dstPort==443))return Application.HTTPS;return Application.UNKNOWN;}
 static Application classify(String d){String x=d==null?"":d.toLowerCase(Locale.ROOT);for(var e:APPS.entrySet())if(x.equals(e.getKey())||x.endsWith("."+e.getKey())||x.contains(e.getKey()))return e.getValue();return Application.UNKNOWN;}
 static String dns(byte[]b){if(b.length<13)return "";int o=12;StringBuilder s=new StringBuilder();while(o<b.length){int n=b[o++]&255;if(n==0)break;if((n&0xc0)!=0||o+n>b.length)return "";if(s.length()>0)s.append('.');s.append(new String(b,o,n,StandardCharsets.ISO_8859_1));o+=n;}return s.toString();}
 static String sni(byte[]b,int o,int n){try{if(n<43|| (b[o]&255)!=22)return null;int p=o+5+4+2+32;int sid=b[p]&255;p+=1+sid;int cs=((b[p]&255)<<8)|(b[p+1]&255);p+=2+cs;int comp=b[p]&255;p+=1+comp;int extLen=((b[p]&255)<<8)|(b[p+1]&255);p+=2;int end=Math.min(o+n,p+extLen);while(p+4<=end){int type=((b[p]&255)<<8)|(b[p+1]&255),len=((b[p+2]&255)<<8)|(b[p+3]&255);p+=4;if(p+len>end)break;if(type==0&&len>=5){int q=p+2;int nameLen=((b[q]&255)<<8)|(b[q+1]&255);q+=2;if(q+nameLen<=p+len)return new String(b,q,nameLen,StandardCharsets.US_ASCII);}p+=len;}}catch(Exception ignored){}return null;}
}
